_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  ROI_KEYPOINT_HEAD: 
    NUM_KEYPOINTS: 39
  # WEIGHTS: "/media/sy/1746fa4b-7555-471c-81e9-023fab575569/doc/data/outputs/keypointsTransfersy_v2_3_720_little/model_0000999.pth"
  WEIGHTS: "/mnt/data/samples/models/model_final_04e291keypoints_50.pkl"
  RESNETS: 
    # DEPTH: 50
    DEPTH: 50
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 4
  # BASE_LR: 0.0005
  BASE_LR: 0.0005
  REFERENCE_WORLD_SIZE: 2
  STEPS: (6400, 7200)
  MAX_ITER: 8000
  CHECKPOINT_PERIOD: 2000
OUTPUT_DIR: "/mnt/data/new_mergeDataToModel/models_right_up_wai_gan_pi_xin"  

DATASETS:
  TRAIN: ("sytrain",)
  TEST: ("sytest",)
TEST:
  EVAL_PERIOD: 200
INPUT:
  # RANDOM_FLIP: "vertical"
  RANDOM_FLIP: "none"
  # ROTATION_ANGLES: (0)

  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)  
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280 
  MIN_SIZE_TRAIN: (720,)
  MAX_SIZE_TRAIN: 1280