DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TEST: ('middle_neck_middle_down_wai_test',)
  TRAIN: ('middle_neck_middle_down_wai_train',)
INPUT:
  MAX_SIZE_TEST: 320
  MAX_SIZE_TRAIN: 320
  MIN_SIZE_TEST: 180
  MIN_SIZE_TRAIN: (180,)
  RANDOM_FLIP: none
MODEL:
  RESNETS:
    DEPTH: 50
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 4
  WEIGHTS: /mnt/dlData/samples/models/model_final_04e291keypoints_50.pkl
OUTPUT_DIR: /mnt/dlData/HFoutputs/models/2021_02_08/middle_neck_middle_down_wai
SOLVER:
  BASE_LR: 0.0005
  CHECKPOINT_PERIOD: 2000
  IMS_PER_BATCH: 16
  MAX_ITER: 8000
  REFERENCE_WORLD_SIZE: 2
  STEPS: (5000, 6000,7000)
TEST:
  EVAL_PERIOD: 200
_BASE_: Base-Keypoint-RCNN-FPN.yaml
